import pandas as pd

#acquisition_sample = pd.read_csv("acquisition_sample.csv")
#agricultural_acquisition = pd.read_csv("agricultural_acquisition.csv")
#all_downloaded_table_record_counts = pd.read_csv("all_downloaded_table_record_counts.csv")
#branded_food = pd.read_csv("branded_food.csv")
food = pd.read_csv("food.csv")
#food_attribute = pd.read_csv("food_attribute.csv")
#food_attribute_type = pd.read_csv("food_attribute_type.csv")
#food_calorie_conversion_factor = pd.read_csv("food_calorie_conversion_factor.csv")
#food_category = pd.read_csv("food_category.csv")
#food_component = pd.read_csv("food_component.csv")
food_nutrient = pd.read_csv("food_nutrient.csv")
#food_nutrient_conversion_factor = pd.read_csv("food_nutrient_conversion_factor.csv")
#food_nutrient_derivation = pd.read_csv("food_nutrient_derivation.csv")
#food_nutrient_source = pd.read_csv("food_nutrient_source.csv")
#food_portion = pd.read_csv("food_portion.csv")
#food_protein_conversion_factor = pd.read_csv("food_protein_conversion_factor.csv")
#food_update_log_entry = pd.read_csv("food_update_log_entry.csv")
#foundation_food = pd.read_csv("foundation_food.csv")
#input_food = pd.read_csv("input_food.csv")
#lab_method = pd.read_csv("lab_method.csv")
#lab_method_code = pd.read_csv("lab_method_code.csv")
#lab_method_nutrient = pd.read_csv("lab_method_nutrient.csv")
#market_acquisition = pd.read_csv("market_acquisition.csv")
#measure_unit = pd.read_csv("measure_unit.csv")
nutrient = pd.read_csv("nutrient.csv")
#nutrient_incoming_name = pd.read_csv("nutrient_incoming_name.csv")
#retention_factor = pd.read_csv("retention_factor.csv")
#sample_food = pd.read_csv("sample_food.csv")
#sub_sample_food = pd.read_csv("sub_sample_food.csv")
#sub_sample_result = pd.read_csv("sub_sample_result.csv")
#survey_fndds_food = pd.read_csv("survey_fndds_food.csv")
#wweia_food_category = pd.read_csv("wweia_food_category.csv")
newnutrient = food_nutrient.set_index('nutrient_id').join(nutrient.set_index('id'))
newnutrient.index.name = 'nutrient_id'
iterlist = newnutrient['name'].unique()
for i in range(len(iterlist)):
	test = iterlist[i]
	nutrientjoin = newnutrient[newnutrient['name'] == test]
	#export_csv = nutrientjoin.to_csv("test.csv")
	if i == 0:
		hypertest = food.set_index('fdc_id').join(nutrientjoin.set_index('fdc_id'))
		hypertest.index.name = 'fdc_id'
		#export_csv = hypertest.to_csv("newcsv.csv")
		#print(hypertest.columns)
		#print("did first")
	else:
		#print(hypertest.columns)
		#print(nutrientjoin.columns)
		hypertest = hypertest.join(nutrientjoin.set_index('fdc_id'), rsuffix=iterlist[i])
		hypertest.index.name = 'fdc_id'
#hypertest = newnutrient.set_index('fdc_id').join(food.set_index('fdc_id'))
#hypertest = hypertest.groupby(hypertest.index)
export_csv = hypertest.to_csv("combined.csv")