version: '3'
services:
  web:
    image: httpd:alpine
    ports:
      - 80:80
    volumes:
      - ./web:/usr/local/apache2/htdocs
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=foodthings
    ports:
      - 8081:8081
      
    volumes:
      - ./database/data:/data/db
      - ./database/db-init:/docker-entrypoint-initdb.d
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app/src
