version: '3'
services:
  web:
    image: httpd:alpine
    ports:
      - 80:80
    volumes:
      - ./web:/usr/local/apache2/htdocs
  database:
    image: mongo
    ports:
      - 8081:8081
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app/src
